export const USER_STORE_NAME: string = 'userStore';

export class AppRoutes {
  static INDEX: string = 'pages/Index';
  static BIND_CAR: string = 'pages/BindCar';
  static BIND_SUCCESS: string = 'pages/BindSuccess';
  static HOME: string = 'pages/Home';
}

export class PreferenceKeys {
  static IS_LOGIN: string = 'isLogin';
  static IS_CAR_BOUND: string = 'isCarBound';
  static TOKEN: string = 'token';
  static USERNAME: string = 'username';
  static USER_ID: string = 'userId';
  static CAR_VIN: string = 'carVin';
  static CAR_ID: string = 'carId';
  static NICK_NAME: string = 'nickName';
  static PHONE_NUMBER: string = 'phonenumber';
  static BIRTH_DATE: string = 'birthDate';
}
